#!/bin/bash
#
# Perform necessary boostrapping to be able to build project with pants (should probably be run once only)

source build-support/scripts/common

SCALA_VER='2.10.4'

# java
if ! type java > /dev/null; then
  sudo add-apt-repository -y ppa:webupd8team/java
  sudo apt-get update
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 seen true   | sudo debconf-set-selections
  sudo apt-get -y install oracle-java8-installer
fi

# scala
if ! type scala > /dev/null; then
  sudo wget http://downloads.typesafe.com/scala/$SCALA_VER/scala-$SCALA_VER.deb
  sudo dpkg -i scala-$SCALA_VER.deb
  sudo apt-get update
  sudo apt-get -y install scala
  sudo rm -f scala-$SCALA_VER.deb
fi

# pip
sudo apt-get -y install python-pip python-dev

# pants
sudo pip install pantsbuild.pants

# vagrant
